# Project configuration
NAME=ft-test
SRC_DIR=src/
VERSION=1.0.10
LOCAL_PORT=3537
GITHUB_USER=filethis
GITHUB_USER_ABBREV=ft
BOWER_NAMESPACE=FileThis
QUERY_STRING=
CDN_DISTRIBUTION_ID=EJ2RMYD38WUXM
PUBLICATION_DOMAIN=connect.filethis.com
AWS_VAULT_PROFILE=filethis

include project-application.make
